---
# Main task file for matrix-element-call

- tags:
    - setup-all
    - setup-jwt-service
    - install-all
    - install-wt-service
  block:
    - when: matrix_jwt_service_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_jwt_service_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-jwt-service
  block:
    - when: not matrix_jwt_service_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"