---

- tags:
    - setup-all
    - setup-jwt-service
    - install-all
    - install-livekit-jwt-service
  block:
    - when: matrix_livekit_jwt_service_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: matrix_livekit_jwt_service_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-livekit-jwt-service
  block:
    - when: not matrix_livekit_jwt_service_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
