---

- name: Fail if required LiveKit JWT Service settings are not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] | length == 0"
  with_items:
    - {'name': 'matrix_livekit_jwt_service_hostname', when: true}
    - {'name': 'matrix_livekit_jwt_service_container_network', when: true}
    - {'name': 'matrix_livekit_jwt_service_environment_variable_livekit_key', when: true}
    - {'name': 'matrix_livekit_jwt_service_environment_variable_livekit_url', when: true}
    - {'name': 'matrix_livekit_jwt_service_environment_variable_livekit_secret', when: true}
