---
# Validate configuration for matrix-element-call

- name: Fail if required matrix-element-call settings are not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] == ''"
  with_items:
    - {'name': 'matrix_element_call_base_path', when: true}
    - {'name': 'matrix_element_call_container_network', when: true}
    - {'name': 'matrix_element_call_image', when: true}
    - {'name': 'matrix_jwt_service_image', when: true}
    - {'name': 'matrix_livekit_image', when: true}
    - {'name': 'redis_image', when: true}
    - {'name': 'matrix_element_call_livekit_dev_key', when: true}
    - {'name': 'matrix_jwt_service_url', when: true}
