# SPDX-FileCopyrightText: 2022 MDAD project contributors
# SPDX-FileCopyrightText: 2024 wjbeckett
# SPDX-FileCopyrightText: 2024 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Fail if required LiveKit Server settings are not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item.name }}`).
  when: "item.when | bool and vars[item.name] | length == 0"
  with_items:
    - {'name': 'livekit_server_hostname', when: true}
    - {'name': 'livekit_server_identifier', when: true}
    - {'name': 'livekit_server_uid', when: true}
    - {'name': 'livekit_server_gid', when: true}
